# Quetion : 1

 Ordinal Encoding is used when the categories of a categorical variable have a natural order, whereas Label Encoding is used when there is no inherent ordering. For example, if we have a categorical variable "Education level" with categories "High School", "Bachelor's", "Master's", and "PhD", we would use Ordinal Encoding because there is a clear order to the categories. However, if we have a categorical variable "Color" with categories "Red", "Green", and "Blue", we would use Label Encoding because there is no inherent order to the colors.

# Quetion : 2

 Target Guided Ordinal Encoding is a technique where we use the target variable to assign ranks to the categories of a categorical variable. For example, if we have a categorical variable "City" with categories "New York", "Los Angeles", and "Chicago", and we are trying to predict the price of a house in each city, we can use the median price of houses in each city to assign a rank to each category. We would then replace the category with its rank. Target Guided Ordinal Encoding is useful when the categorical variable is strongly correlated with the target variable and has a monotonic relationship with it.

# Quetion : 3

Covariance is a measure of the degree of association between two variables. It indicates how much two variables change together, and in what direction. Covariance is important in statistical analysis because it helps us understand the relationship between variables and can be used to make predictions. Covariance is calculated by taking the product of the deviations of each variable from its mean, and then dividing by the sample size.

# Quetion : 4

In [1]:
import pandas as pd
data = {'Color': ['red', 'green', 'blue', 'red', 'green', 'blue'],
        'Size': ['small', 'medium', 'large', 'medium', 'small', 'large'],
        'Material': ['wood', 'metal', 'plastic', 'plastic', 'wood', 'metal']}

df = pd.DataFrame(data)
from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()


In [3]:
df['Color'] = lbl_encoder.fit_transform(df['Color'])
df['Size'] = lbl_encoder.fit_transform(df['Size'])
df['Material'] = lbl_encoder.fit_transform(df['Material'])
df

Color  Size  Material
0      2     2         2
1      1     1         0
2      0     0         1
3      2     1         1
4      1     2         2
5      0     0         0

# Quetion : 5

In [6]:
import numpy as np
data = np.array([[25, 50000, 3],
                 [30, 60000, 4],
                 [35, 70000, 4],
                 [40, 80000, 5],
                 [45, 90000, 5]])

covariance_matrix = np.cov(data, rowvar=False)

print(covariance_matrix)

[[6.25e+01 1.25e+05 6.25e+00]
 [1.25e+05 2.50e+08 1.25e+04]
 [6.25e+00 1.25e+04 7.00e-01]]


# Quetion : 6

For "Gender", we would use label encoding because there is no inherent order between Male and Female.

For "Education Level", we would use ordinal encoding because there is a natural order between the different levels of education (i.e., PhD > Master's > Bachelor's > High School).

For "Employment Status", we would also use ordinal encoding because there is a natural order between the different levels of employment (i.e., Full-Time > Part-Time > Unemployed).

# Quetion : 7